export const worksList = [
   {
      id: "1",
      title: "Débogage et mise en place de tests pour un SaaS RH",
      cover: "/portfolio/images/covers/Work1Cover.jpg",
      gallery: [
         {
            type: "Desktop",
            images: [
               "/portfolio/images/Work1/Desktop/Work1DashboardEmployeeDesktop.jpg",
               "/portfolio/images/Work1/Desktop/Work1DashboardRHDesktop.jpg",
            ],
         },
      ],
      intro: "Sur ce projet, ma tâche était d'identifier et de corriger les bugs présents. J'ai également écrit les tests (unitaires, intégration, plan de tests End-To-End) et atteint un taux moyen de couverture de 92%.",
      techs: ["Jest", "JavaScript", "CSS3", "Méthode agile"],
      search: [
         "Jest",
         "Chrome Debugger",
         "JavaScript",
         "Testing Library",
         "NPM",
         "Méthode agile",
      ],
      type: "Formation",
      time: "5",
      urlDemo: "https://verapandi.github.io/",
      urlGithub: "https://github.com/VeraPandi/portfolio",
   },
   {
      id: "3",
      title: "Développement d’un tableau de bord d'analytics",
      cover: "/portfolio/images/covers/Work3Cover1.jpg",
      gallery: [
         {
            type: "Desktop",
            images: [
               "/portfolio/images/Work3/Desktop/Work3Profile1Desktop.jpg",
               "/portfolio/images/Work3/Desktop/Work3Profile2Desktop.jpg",
            ],
         },
      ],
      intro: "Pour le compte d'une startup dédiée au coaching sportif, j'ai été chargée d'intégrer des graphiques de suivi d'activité sportive quotidienne à la page profil des utilisateurs. Au cours de la réalisation de ce projet, j'ai intégré la maquette desktop ; développé les graphiques permettant à l'utilisateur de suivre sa progression sportive et calorique ; produit une documentation technique.",
      techs: [
         "Create React App",
         "React",
         "JavaScript",
         "API REST",
         "Postman",
         "Sass",
         "Recharts",
         "Méthode agile",
      ],
      search: [
         "JavaScript",
         "Create React App",
         "React Router",
         "Sass",
         "React",
         "API REST",
         "Responsive",
         "Méthode agile",
         "Recharts",
         "Postman",
         "Proptypes",
         "JsDoc",
         "Yarn",
      ],
      type: "Formation",
      time: "4",
      urlDemo: "https://verapandi.github.io/",
      urlGithub: "https://github.com/VeraPandi/portfolio",
   },
   {
      id: "4",
      title: "Utilisation d’une API pour un compte utilisateur bancaire",
      cover: "/portfolio/images/covers/Work4Cover.jpg",
      gallery: [
         {
            type: "Desktop",
            images: [
               "/portfolio/images/Work4/Desktop/Work4HomeDesktop.jpg",
               "/portfolio/images/Work4/Desktop/Work4FormDesktop.jpg",
            ],
         },
         {
            type: "Mobile",
            images: [
               "/portfolio/images/Work4/Mobile/Work4HomeMobile.jpg",
               "/portfolio/images/Work4/Mobile/Work4FormMobile.jpg",
            ],
         },
      ],
      intro: "Dans le cadre de cette mission, j'ai été chargée de créer une application bancaire responsive permettant aux clients de se connecter et de gérer leur compte et profil. Au cours de sa réalisation, j'ai intégré les maquettes de l'application ; implémenté un gestionnaire d'état ; modélisé une API des transactions bancaires en suivant les directives Swagger.",
      techs: [
         "Create React App",
         "React",
         "JavaScript",
         "React Redux",
         "API REST",
         "MongoDB",
         "Swagger",
         "Sass",
         "Méthode agile",
      ],
      search: [
         "Postman",
         "MongoDB",
         "NPM",
         "Swagger",
         "React Redux",
         "JavaScript",
         "Create React App",
         "React Router",
         "Sass",
         "React",
         "API REST",
         "Responsive",
         "Méthode agile",
      ],
      type: "Formation",
      time: "5",
      urlDemo: "https://verapandi.github.io/",
      urlGithub: "https://github.com/VeraPandi/portfolio",
   },
   {
      id: "5",
      title: "Conversion d’une application web interne jQuery en React",
      cover: "/portfolio/images/covers/Work5Cover.jpg",
      gallery: [
         {
            type: "Desktop",
            images: [
               "/portfolio/images/Work5/Desktop/Work5FormDesktop.jpg",
               "/portfolio/images/Work5/Desktop/Work5TableDesktop.jpg",
            ],
         },
      ],
      intro: "Dans le cadre de cette mission, j'ai été chargée de convertir une application web interne JQuery en React afin de réduire sa dette technique. Au cours de sa réalisation, j'ai converti l'ensemble de ses fonctionnalités en React ; créé un design responsive plus moderne et lisible pour les utilisateurs ; implémenté un gestionnaire d'état ; audité les performances pour les maintenir à leur meilleur niveau ; converti une fonctionnalité de l'application en plugin, qu'ensuite j'ai publié sur NPM.",
      techs: [
         "Create React App",
         "React",
         "JavaScript",
         "Redux Toolkit",
         "Sass",
         "Material UI",
         "NPM",
         "Méthode agile",
      ],
      search: [
         "Create React App",
         "React",
         "React Router",
         "JavaScript",
         "Redux Toolkit",
         "Material UI",
         "Sass",
         "NPM",
         "JsDoc",
         "Maquettage",
         "Plugin",
         "Lighthouse",
         "Méthode agile",
      ],
      type: "Formation",
      time: "3",
      urlDemo: "https://verapandi.github.io/",
      urlGithub: "https://github.com/VeraPandi/portfolio",
   },
   {
      id: "6",
      title: "Portfolio",
      cover: "/portfolio/images/covers/Work6Cover.jpg",
      gallery: [
         {
            type: "Desktop",
            images: [
               "/portfolio/images/Work6/Desktop/Work6HomeDesktop.jpg",
               "/portfolio/images/Work6/Desktop/Work6ProjectsDesktop.jpg",
            ],
         },
         {
            type: "Mobile",
            images: [
               "/portfolio/images/Work6/Mobile/Work6HomeMobile.jpg",
               "/portfolio/images/Work6/Mobile/Work6ProjectsMobile.jpg",
            ],
         },
      ],
      intro: "Pour mon portfolio, j'ai voulu créer une application simple, qui va à l'essentiel, contenant une présentation et mes projets réalisés. Quant aux choix techniques que j'ai faits, j'ai souhaité développer mon application uniquement en React, JavaScript et Scss, sans utilisation de bibliothèques. Mon objectif était de continuer à développer et consolider mes connaissances en Javascript et React.",
      techs: [
         "Create React App",
         "React",
         "JavaScript",
         "Jest",
         "Cypress",
         "Sass",
      ],
      search: [
         "Create React App",
         "React",
         "React Router",
         "JavaScript",
         "Sass",
         "Jest",
         "Testing Library",
         "Cypress",
         "NPM",
         "JsDoc",
         "Responsive",
         "Accessibilité",
         "WCAG",
         "Lighthouse",
         "Maquettage",
      ],
      type: "Side project",
      time: "4",
      urlDemo: "https://verapandi.github.io/portfolio/",
      urlGithub: "https://github.com/VeraPandi/portfolio",
   },
];
