export const worksList = [
   {
      id: "9",
      title: "Débogage et mise en place de tests pour un SaaS RH",
      cover: "/portfolio/images/covers/Work9Cover.jpg",
      gallery: [
         {
            type: "Desktop",
            images: [
               "/portfolio/images/Work9/Desktop/Work9DashboardEmployeeDesktop.jpg",
            ],
         },
      ],
      intro: "Dans le cadre de cette mission, j'ai été chargée de débugger et tester le SaaS RH de l'entreprise pour le compte Administrateur RH et le compte Employé. Au cours de cette mission, j'ai identifié et corrigé les bugs de l'application ; écrit les tests unitaires et d’intégration ; rédigé le plan de tests End-To-End pour le compte Employé ; réalisé un rapport de tests et de couverture. Suite à mon travail, le taux moyen de couverture a atteint 92%.",
      techs: [
         "Jest",
         "Testing Library",
         "JavaScript",
         "CSS3",
         "GitHub Pages",
         "Méthode agile",
      ],
      search: [
         "Jest",
         "Chrome Debugger",
         "JavaScript",
         "Testing Library",
         "NPM",
         "NodeJS",
         "GitHub Pages",
         "Méthode agile",
      ],
      startDate: "02/22",
      type: "Formation",
      time: "5",
      member: "Seule",
      urlGithub: "https://github.com/VeraPandi/billed",
   },
   {
      id: "12",
      title: "Développement d’un tableau de bord d'analytics",
      cover: "/portfolio/images/covers/Work12Cover1.jpg",
      gallery: [
         {
            type: "Desktop",
            images: [
               "/portfolio/images/Work12/Desktop/Work12Profile1Desktop.jpg",
            ],
         },
      ],
      intro: "Pour le compte de SportSee, une startup dédiée au coaching sportif, j'ai été chargée d'intégrer des graphiques de suivi d'activité sportive quotidienne à la page profil des utilisateurs. Au cours de la réalisation de ce projet, j'ai intégré la maquette desktop ; utilisé la bibliothèque Recharts pour développer les graphiques ; produit une documentation technique.",
      techs: [
         "Create React App",
         "React",
         "JavaScript",
         "API REST",
         "Postman",
         "Sass",
         "Recharts",
         "GitHub Pages",
         "Méthode agile",
      ],
      search: [
         "JavaScript",
         "Create React App",
         "React Router",
         "Sass",
         "React",
         "API REST",
         "Responsive",
         "Méthode agile",
         "Recharts",
         "Postman",
         "Proptypes",
         "JsDoc",
         "NodeJS",
         "GitHub Pages",
         "Yarn",
      ],
      startDate: "05/22",
      type: "Formation",
      time: "4",
      member: "Seule",
      urlDemo: "https://verapandi.github.io/sportsee/user/18",
      urlGithub: "https://github.com/VeraPandi/sportsee",
   },
   {
      id: "13",
      title: "Utilisation d’une API pour un compte utilisateur bancaire",
      cover: "/portfolio/images/covers/Work13Cover.jpg",
      gallery: [
         {
            type: "Desktop",
            images: ["/portfolio/images/Work13/Desktop/Work13HomeDesktop.jpg"],
         },
         {
            type: "Mobile",
            images: ["/portfolio/images/Work13/Mobile/Work13HomeMobile.jpg"],
         },
      ],
      intro: "Pour une nouvelle banque, j'ai été chargée de créer une application bancaire responsive permettant aux clients de se connecter et de gérer leur compte et profil. Au cours de la réalisation du projet, j'ai intégré les maquettes de l'application ; implémenté React Redux en tant que gestionnaire d'état ; modélisé une API des transactions bancaires en suivant les directives OpenAPI.",
      techs: [
         "Create React App",
         "React",
         "JavaScript",
         "React Redux",
         "API REST",
         "MongoDB",
         "OpenAPI",
         "Sass",
         "GitHub Pages",
         "Méthode agile",
      ],
      search: [
         "Postman",
         "MongoDB",
         "NPM",
         "OpenAPI",
         "React Redux",
         "JavaScript",
         "Create React App",
         "React Router",
         "Sass",
         "React",
         "API REST",
         "Responsive",
         "NodeJS",
         "GitHub Pages",
         "Méthode agile",
      ],
      startDate: "06/22",
      type: "Formation",
      time: "5",
      member: "Seule",
      urlDemo: "https://verapandi.github.io/argent-bank/",
      urlGithub: "https://github.com/VeraPandi/argent-bank",
   },
   {
      id: "14",
      title: "Conversion d’une application web interne jQuery en React",
      cover: "/portfolio/images/covers/Work14Cover.jpg",
      gallery: [
         {
            type: "Desktop",
            images: ["/portfolio/images/Work14/Desktop/Work14FormDesktop.jpg"],
         },
      ],
      intro: "Pour le compte de Wealthhealth, j'ai été chargée de convertir l'application web interne JQuery en React afin de réduire sa dette technique. Au cours de la réalisation de ce livrable, j'ai converti l'ensemble des fonctionnalités en React ; créé un design plus moderne et lisible pour les utilisateurs à l'aide de la bibliothèque Material UI ; implémenté Redux Toolkit en tant que gestionnaire d'état ; audité les performances avec Lighthouse ; converti la modale de l'application en plugin, qu'ensuite j'ai publié sur NPM.",
      techs: [
         "Maquettage",
         "Create React App",
         "React",
         "JavaScript",
         "Redux Toolkit",
         "Sass",
         "Material UI",
         "NPM",
         "Lighthouse",
         "GitHub Pages",
         "Méthode agile",
      ],
      search: [
         "Create React App",
         "React",
         "React Router",
         "JavaScript",
         "Redux Toolkit",
         "Material UI",
         "Sass",
         "NPM",
         "JsDoc",
         "Maquettage",
         "Plugin",
         "Lighthouse",
         "NodeJS",
         "GitHub Pages",
         "Méthode agile",
      ],
      startDate: "07/22",
      type: "Formation",
      time: "3",
      member: "Seule",
      urlDemo: "https://verapandi.github.io/wealthhealth/",
      urlGithub: "https://github.com/VeraPandi/wealthhealth",
   },
   {
      id: "15",
      title: "Création d'un portfolio",
      cover: "/portfolio/images/covers/Work15Cover.jpg",
      gallery: [
         {
            type: "Desktop",
            images: ["/portfolio/images/Work15/Desktop/Work15HomeDesktop.jpg"],
         },
         {
            type: "Mobile",
            images: ["/portfolio/images/Work15/Mobile/Work15HomeMobile.jpg"],
         },
      ],
      intro: "Pour mon portfolio, j'ai voulu créer une application simple, qui va à l'essentiel, contenant une brève présentation et mes projets réalisés. J'ai souhaité la développer uniquement avec React, JavaScript, Sass, Jest et Cypress, sans utilisation de bibliothèques supplémentaires, car mon objectif était de continuer à développer mes connaissances en JavaScript et React, ainsi qu'à m'exercer à écrire des tests avec Cypress. Au cours de la réalisation de ce projet, j'ai créé la maquette de l'application ; intégré la maquette ; appliqué les directives liées à l'accessibilité ; testé avec Jest et Cypress les données et composants qui me semblaient à risque ; écrit les tests End-To-End de toutes les pages dans le but principal d'utiliser plus en profondeur Cypress ; audité les performances avec Lighthouse.",
      techs: [
         "Maquettage",
         "Create React App",
         "React",
         "JavaScript",
         "Jest",
         "Testing Library",
         "Cypress",
         "Sass",
         "WCAG",
         "Lighthouse",
         "GitHub Pages",
      ],
      search: [
         "Create React App",
         "React",
         "React Router",
         "JavaScript",
         "Sass",
         "Jest",
         "Testing Library",
         "Cypress",
         "NPM",
         "JsDoc",
         "Responsive",
         "Accessibilité",
         "WCAG",
         "Lighthouse",
         "Maquettage",
         "NodeJS",
         "GitHub Pages",
      ],
      startDate: "08/22",
      type: "Side project",
      time: "4",
      member: "Seule",
      urlDemo: "https://verapandi.github.io/portfolio/",
      urlGithub: "https://github.com/VeraPandi/portfolio",
   },
   {
      id: "16",
      title: "Création d'un puzzle Jigsaw",
      cover: "/portfolio/images/covers/Work16Cover.jpg",
      gallery: [
         {
            type: "Desktop",
            images: ["/portfolio/images/Work16/Desktop/Work16LoginDesktop.jpg"],
         },
         {
            type: "Tablet",
            images: ["/portfolio/images/Work16/Tablet/Work16LoginTablet.jpg"],
         },
      ],
      intro: "Dans ce nouveau projet, j'ai souhaité créer un puzzle Jigsaw classique. Jusqu'à maintenant, ce projet est celui qui a été le plus long et le plus complexe à créer. En effet, il m'a fallu apprendre 6 nouveaux outils pour le réaliser. Il m'a demandé un gros travail de recherche, d'apprentissage, d'approfondissement, de tests et d'écriture de code. Etant donné que c'est mon premier essai, seule, sur de nombreux outils que je ne connaissais pas auparavant, j'ai conscience que le résultat demande encore des améliorations. Néanmoins, pour une première approche, je suis relativement satisfaite du résultat et d'en arriver bientôt à bout. Au cours de la réalisation de ce projet, j'ai créé la maquette de l'application ; intégré la maquette desktop et tablette avec TailwindCSS ; implémenté Zustand en tant que gestionnaire d'état et Firebase Realtime Database en tant que base de données ; utilisé la bibliothèque Headbreaker pour développer le plateau du jeu ; déployé l'application avec Netlify.",
      techs: [
         "Maquettage",
         "Create React App",
         "React",
         "JavaScript",
         "TypeScript",
         "API REST",
         "Postman",
         "Zustand",
         "Firebase Realtime Database",
         "TailwindCSS",
         "Headbreaker",
         "Netlify",
      ],
      search: [
         "Create React App",
         "React",
         "React Router",
         "JavaScript",
         "NPM",
         "Responsive",
         "Accessibilité",
         "WCAG",
         "Maquettage",
         "NodeJS",
         "Serverless functions",
         "Firebase Realtime Database",
         "Cloud Firestore",
         "TypeScript",
         "API REST",
         "Postman",
         "Zustand",
         "Firebase",
         "TailwindCSS",
         "Headbreaker",
         "Netlify",
      ],
      startDate: "02/23",
      type: "Side project",
      time: "17",
      member: "Seule",
      urlDemo: "https://vp-jigsaw-puzzle.netlify.app/",
      urlGithub: "https://github.com/VeraPandi/puzzle",
   },
];
