export const skills = {
   frontEnd: [
      "HTML",
      "CSS",
      "JavaScript",
      "Styled Components",
      "Git",
      "GitHub",
      "Jest",
      "Testing Library",
      "JSDoc",
      "Redux",
      "React Redux",
      "ReactJS",
      "NPM",
      "Yarn",
      "React Router DOM",
      "Plugin",
      "Recharts",
      "CRA",
      "Create React App",
      "Redux Toolkit",
      "Material UI",
      "Lighthouse",
   ],
   backEnd: ["NodeJS", "MongoDB"],
};
